[package]
name = "id_allocator"
version = "0.1.0"
edition = "2018"
authors = ["Campbell He (duskmoon)"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
